server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/apidoc?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
  jpa:
    show-sql: true