server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/apidoc?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update